#%RAML 1.0 DataType

Cache-Control:
  description: |
   Can be used to specify caching behavior along the request/reply chain. Added default max-age as 15 min.
  type: string
  required: true
  example: private, max-age=900
